name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish -o deploy    
      
    # - name: FTP Deploy
    # # You may pin to the exact commit or the version.
    # # uses: SamKirkland/FTP-Deploy-Action@da0d77ff390a13097c60f9b9eb954e503a480d97
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.1
    #   with:
    #   # Deployment destination server & path. Formatted as
    #     ftp-server: ${{ secrets.FTP_SERVER }}
    #     # FTP account username
    #     ftp-username: ${{ secrets.FTP_USER }}
    #     # FTP account password
    #     ftp-password: ${{ secrets.FTP_PWD }}
    #     # The local folder to copy, defaults to root project folder
    #     local-dir: deploy/
    #     # Passes through options into git-ftp
    #     #git-ftp-args: # optional
   
        
    # - name: 'Run Azure webapp deploy action using publish profile credentials'
    #   uses: Azure/webapps-deploy@v1
    #   with: 
    #     app-name: partidoonline # Replace with your app name
    #     publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE  }} # Define secret variable in repository settings as per action documentation
    #     package: './dotnetcorewebapp'
    

   
